from html import escape
def html_block(title,body):return f'<b>{escape(title)}</b>\n<blockquote expandable>{escape(body)}</blockquote>'
def preview_task(t):return f"<b>{escape(t['_id'])}</b> | {'ON' if t.get('enabled') else 'OFF'} | <i>{len(t.get('sources',[]))} source → {len(t.get('targets',[]))} target</i> | copy={t.get('copy_mode',True)}"
def menu_text(user):
    body='Auto Forward helps you route updates between channels, groups, bots, and private chats without manual copying.\n\nBuild reliable forwarding flows, filters, cloning, edit/delete sync, and delivery rules in one place.\n\nUse /connect to link your Telegram account.'
    return f'<b>Hello Senator ?! 👋</b>\n\n<i>Professional forwarding control center.</i>\n\n<blockquote expandable>{escape(body)}</blockquote>'
def guide_text():
    body='📋 Core\n/start — Open the main menu\n/restart — Owner restart\n\n📨 Forwarding\n/forward — Create and manage forwarding tasks\n/spam — Review smart mass-send tasks\n/publish — Review publishing tasks\n/task_on — Enable task\n/task_off — Disable task\n/forward_header — Toggle visible forward header\n\n🔍 Filters\n/replace — Manage replace rules\n/whitelist — Manage allow-list rules\n/blacklist — Manage block-list rules\n/filter_users — Manage sender allow/block lists\n/header — Add permanent header\n/footer — Add permanent footer\n/delay — Set task delay\n\n💬 Chat Discovery\n/getchannel — List your channels\n/getgroup — List your groups\n/getuser — List private chats\n/getbot — List bot chats\n\n👤 Account\n/profile — Open profile\n/settings — Open settings\n/language — Change language\n/upgrade — View plans\n/make_money — Open referrals\n/get_app — Get app links\n/connect — Connect Telegram account\n/disconnect — Disconnect account\n\n🛡 Owner\n/gban — Globally ban a user\n/ungban — Remove global ban\n/gbanlist — Show global bans\n/sessions — List connected sessions\n/session_status — Inspect a session\n/session_delete — Delete a session\n/session_add — Add session file by reply\n/get_session — Export owner-owned session only\n\n📦 Clone\n/clone — Clone past messages between chats'
    return f'<b>❓ Command Guide</b>\n\n<blockquote expandable>{escape(body)}</blockquote>'
